### ISSUE TITLE
NameError: name 'face_mask_tensor' is not defined

### ISSUE THREAD

**Issue by l1iquan** [antgroup/echomimic_v2#12]
NameError: name 'face_mask_tensor' is not defined

**Comment by l1iquan** [comment]
help me！

**Comment by zhuzcuolis** [comment]
there,it's worth a try[NameError: name 'face_mask_tensor' is not defined](https://github.com/antgroup/echomimic_v2/pull/8)

**Comment by gluttony-10** [comment]
> NameError: name 'face_mask_tensor' is not defined

See [pull #8 ](https://github.com/antgroup/echomimic_v2/pull/8)

**Comment by l1iquan** [comment]
thanks！

**Comment by mengrang** [comment]
fixed
