### ISSUE TITLE
关于生成视频的时长限制

### ISSUE THREAD

**Issue by cmmclee** [antgroup/echomimic_v2#19]
请教：我输入一段长音频，结果输出的视频时长只有14秒。是有什么时长限制吗？谢谢

**Comment by wangyang2014** [comment]
生成视频的时长与输入的音频相关，他们是协同的。生成的视频长度与显存消耗成正比的

**Comment by ahkimkoo** [comment]
> 可以在自己代码里把时长改大

在哪个位置改呢

**Comment by mengrang** [comment]
args.L

**Comment by Lvaho** [comment]
#30 
和这个问题一样，应该是pose文件有限的问题
