### ISSUE TITLE
 No such file or directory: './pretrained_weights/reference_unet-162000.pth'

### ISSUE THREAD

**Issue by lilivsea** [antgroup/echomimic_v2#2]
运行 python infer.py --config='./configs/prompts/infer.yaml'   报错： No such file or directory: './pretrained_weights/reference_unet-162000.pth'
看了下https://huggingface.co/BadToBest/EchoMimic/tree/main上还缺好多模型文件，是没更新吗？ 或者去哪里去下这个项目的模型文件？

**Comment by lymhust** [comment]
稍等一下，模型正在上传huggingface和modelscope，速度比较慢。争取明后天传完。
