### ISSUE TITLE
支持windows部署吗，n卡最低要求多少

### ISSUE THREAD

**Issue by lucklycaicai** [antgroup/echomimic_v2#3]

**Comment by IuvenisSapiens** [comment]
<img width="1280" alt="fb3df81b96afec5f9535a9557c5af2d" src="https://github.com/user-attachments/assets/b778992c-b97c-429a-8e24-1a411b270590">

**Comment by zhuzcuolis** [comment]
![微信图片_20241121193224](https://github.com/user-attachments/assets/c4cbe80f-fe72-4ea8-b746-3b21e781f22c)
满嘞

**Comment by gluttony-10** [comment]
默认推理至少需要18G显存

**Comment by nitinmukesh** [comment]
@IuvenisSapiens 

Did it worked? I don't think it will work on 8 GB VRAM.

**Comment by IuvenisSapiens** [comment]
> @IuvenisSapiens
> 
> Did it worked? I don't think it will work on 8 GB VRAM.

On an **8GB VRAM** graphics card, the inference speed is **extremely slow**, which significantly diminishes its practical use. It is reported that a minimum of 18GB of VRAM is necessary for NVIDIA cards to achieve acceptable performance, indicating that the software is not suitable for use on an 8GB VRAM setup due to the poor inference speed.

**Comment by gluttony-10** [comment]
IuvenisSapiens老哥提了一个pr，可降低显存占用到13G。

**Comment by goodluck821** [comment]
windows系统无法用，
   0.0 seconds (IMPORT FAILED): K:\ComfyUI-aki-v1.4\custom_nodes\echomimic_v2

**Comment by mengrang** [comment]
这个和时长相关，目前约5秒的视频还是需要13G显存的

**Comment by mengrang** [comment]
请参考常见问题5.

**Comment by TryingToDoBetter25** [comment]
Windows系统下部署EchoMimic_v2：
视频：https://www.bilibili.com/video/BV1mhz5YxEf3/?vd_source=669a41b5549159436dfac89400bacf7e
文档：https://cqldg89mjy4.feishu.cn/docx/Ayp7dZehNo1M42x4hkNcX3IAn4e?from=from_copylink

**Comment by gluttony-10** [comment]
欢迎windows系统用户，直接使用一键包：
[https://www.bilibili.com/video/BV1rqBBY2Ekd/](https://www.bilibili.com/video/BV1rqBBY2Ekd/)
