### ISSUE TITLE
如何取消手势生成？

### ISSUE THREAD

**Issue by tianbuwei** [antgroup/echomimic_v2#34]
我现在用这张图片生成视频，发现图像多了双手，如何取消手势的生成？
![man](https://github.com/user-attachments/assets/948f7089-9412-46f3-af47-8674e89fd190)
生成之后是这样的
![image](https://github.com/user-attachments/assets/975a2c9f-604d-4f9b-822e-1b6cdc939c73)

**Comment by mengrang** [comment]
归因到属于pose与图像对齐方面。参考issue13#，稍后提供手势与图像对齐脚本
