### ISSUE TITLE
生成视频变形较大

### ISSUE THREAD

**Issue by tianbuwei** [antgroup/echomimic_v2#35]
您好，我使用自己的图片来生成视频，发现头部效果不太稳定。想请问下，如果使用自己的图片需要重新进行微调吗？
使用的图片：
![sun](https://github.com/user-attachments/assets/1f12628f-64e9-4df5-8aed-1566fe936e24)
生成的视频：
https://github.com/user-attachments/assets/c1cc60ab-3199-43b1-96eb-fe45b1e422a1

**Comment by lymhust** [comment]
大概率是输入图像和pose没做对齐，算法需要严格对齐。相关对齐代码最近会更新到git。

**Comment by mengrang** [comment]
你好，给一下音频文件？ 我们把你的问题当作一个测试样例试一下？

**Comment by tianbuwei** [comment]
> Reference in new issue

您好，感谢您的回复，这是我的音频文件：
[0.wav.zip](https://github.com/user-attachments/files/17900502/0.wav.zip)

**Comment by tianbuwei** [comment]
> 大概率是输入图像和pose没做对齐，算法需要严格对齐。相关对齐代码最近会更新到git。

假如我不需要手部动作，只需要脸部和嘴可以活动，有没有相关的配置呢

**Comment by mengrang** [comment]
你好，我们将你的参考图作为测试示例，对齐之后的结果如下

https://github.com/user-attachments/assets/28bc26d7-9bd1-4cd6-a14d-4f6a62904a16

**Comment by 120805481** [comment]
大佬，如何做对齐。

**Comment by lymhust** [comment]
> > 大概率是输入图像和pose没做对齐，算法需要严格对齐。相关对齐代码最近会更新到git。
> 
> 假如我不需要手部动作，只需要脸部和嘴可以活动，有没有相关的配置呢

没有手部pose目前还不支持

**Comment by tianbuwei** [comment]
> 你好，我们将你的参考图作为测试示例，对齐之后的结果如下
> 
>  test_issue.png-a-test_issue-i0_sig.mp4

您好，这个视频效果很好，请问下该怎么做呢

**Comment by lymhust** [comment]
对齐和pose提取的代码在写了，回头写成一个notebook放到git上面，争取最近几天弄完。

**Comment by tianbuwei** [comment]
> 对齐和pose提取的代码在写了，回头写成一个notebook放到git上面，争取最近几天弄完。

感谢大佬

**Comment by YunjieYu** [comment]
> > > 大概率是输入图像和pose没做对齐，算法需要严格对齐。相关对齐代码最近会更新到git。
> > 
> > 
> > 假如我不需要手部动作，只需要脸部和嘴可以活动，有没有相关的配置呢
> 
> 没有手部pose目前还不支持

按照文章**3.2.2 Audio-Body Correlation**的介绍，Audio实际上是可以驱动半身的（包括手部）。请问现有代码是否可以支持“不使用pose输入，只用audio来实现嘴型和手部的运动”？

**Comment by YunjieYu** [comment]
好的，感谢

**Comment by oylz** [comment]
@tianbuwei Can't wait, can you share the main idea of ​​alignment?

**Comment by Wangyx-123** [comment]
对齐和pose提取的代码什么时候会出来哇

**Comment by junphine** [comment]
我自己输入的图像使用pose1变成长颈鹿了

**Comment by chdaner** [comment]
自定义pose怎么做呢？

**Comment by mengrang** [comment]
https://github.com/antgroup/echomimic_v2/blob/main/demo.ipynb

**Comment by yangrz7** [comment]
> https://github.com/antgroup/echomimic_v2/blob/main/demo.ipynb

请问下我跑了一张2431xx3229的图片用来对齐，但是报如下错误是什么原因呢？

<img width="862" alt="Image" src="https://github.com/user-attachments/assets/9d2c613e-f747-4be0-855e-4378e82baf10" />
