### ISSUE TITLE
可以实现只做手部泛华吗。目前来看整体效果很不理想，头部变形非常严重。可以退而求其次，只做手部的动作驱动，头部口型保持不变吗？

### ISSUE THREAD

**Issue by 120805481** [antgroup/echomimic_v2#36]
目前来看整体效果很不理想，头部变形非常严重。可以退而求其次，只做手部的动作驱动，头部口型保持不变吗？

**Comment by lymhust** [comment]
大概率是输入图像和pose没做对齐，算法需要严格对齐。相关对齐代码最近会更新到git。你这边测试的【原始图、音频、最终结果】能否发一下看看？

**Comment by 120805481** [comment]
[sucai.zip](https://github.com/user-attachments/files/17899706/sucai.zip)
您好。原始图片，音频文件，生成结果在zip里面。您可以下载参考一下。目前pose这个我不知道怎么生成，是用的默认的pose。如果您这个项目优化到可以泛华生成，这个项目的价值会非常大，期待项目持续进步！

**Comment by lymhust** [comment]
https://github.com/antgroup/echomimic_v2/issues/35
参考一下这个，应该和这个是同一个问题

**Comment by mengrang** [comment]
你好，我们将你的参考图作为测试示例，对齐之后的结果可以参考


https://github.com/user-attachments/assets/665e6cb4-eb55-4bb3-8df3-c453b2eab72e
