### ISSUE TITLE
windows下triton模块无法安装

### ISSUE THREAD

**Issue by huang13094467469** [antgroup/echomimic_v2#39]
windows下triton模块装不上：ModuleNotFoundError: No module named 'triton',
我尝试了很多方法，网上也提供了以下比较老的两个whl安装包，但是装上后，在生成视频的时候报错。
最后去了triton的官网，下载了源码来编译安装最新的版本。但是很不幸，我又失败了。
如果您们能提供一下windows下的triton包，就很完美了。

**Comment by mengrang** [comment]
稍后我们会整理一下windows下的安装教程～

**Comment by huang13094467469** [comment]
非常感谢

**Comment by nitinmukesh** [comment]
@huang13094467469 

try the wheels for Windows as explained in this video
https://youtu.be/JORL_67HzJI?si=oqavN7Aty9eD0GWq

**Comment by 360PB** [comment]
> 
从网上找的
Windows builds of Triton(Requires Cuda 12.x)
链接：https://pan.quark.cn/s/9160a06640ce

**Comment by huang13094467469** [comment]
我已经可以在windows下正常的推理了，但是我的4060 Ti 16G ，很慢~

**Comment by wudidiandian** [comment]
好像不装这玩意也能跑，我也是提示这个，但是web页面还能运行，于是跑了echomimicv2_man这个例子，但很慢，16G VRAM跑了快20分钟了，不知道跟没装triton有关系么

**Comment by wudidiandian** [comment]
好像不装这玩意也能跑，我也是提示这个，但是web页面还能运行，于是跑了echomimicv2_man这个例子，但很慢，16G VRAM跑了快20分钟了，不知道跟没装triton有关系么
