### ISSUE TITLE
请问 您数据中的 截取的开始和结束时间是如何获取的呢？？？？

### ISSUE THREAD

**Issue by SevenMpp** [antgroup/echomimic_v2#41]
其中的  Start Timecode,End Timecode 是如何获得的呢？？？？
URL,Start Timecode,End Timecode
https://www.youtube.com/watch?v=NBMTc71yrpk,00:00:54.596,00:01:01.561

**Comment by mengrang** [comment]
使用 slice.sh

**Comment by SevenMpp** [comment]
好的 感谢您的回复 我试试
