### ISSUE TITLE
An error occurred while trying to fetch ./pretrained_weights/sd-image-variations-diffusers: Error no file named diffusion_pytorch_model.safetensors found in directory ./pretrained_weights/sd-image-variations-diffusers.

### ISSUE THREAD

**Issue by 397688551** [antgroup/echomimic_v2#42]
这是我的目录文件，今天下载的模型文件，运行python infer.py的时候说没有这个文件
<img width="260" alt="image" src="https://github.com/user-attachments/assets/ff2a4f28-d2a5-451d-aa6c-f97e44c990a1">

看了模型的仓库，确实也没有这个文件：
<img width="1086" alt="image" src="https://github.com/user-attachments/assets/093907c9-9b92-44ce-b675-c8934138c341">

**Comment by mengrang** [comment]
下载一下最新的EchoMimicV2项目代码

**Comment by 397688551** [comment]
我是最新的代码，还是不行

**Comment by TryingToDoBetter25** [comment]
这里面的网盘链接有完整的模型文件，下载下来粘贴进去就行了https://cqldg89mjy4.feishu.cn/docx/Ayp7dZehNo1M42x4hkNcX3IAn4e?from=from_copylink

**Comment by soledad-deng** [comment]
遇到了同样的问题，有进展木有

**Comment by mengrang** [comment]
we update the automatic installation script for Linux, you can try it.

**Comment by wzr0108** [comment]
我下载最新的代码，还是遇到这个问题

**Comment by mengrang** [comment]
参考#85 
refer to #85

**Comment by wzr0108** [comment]
这个错误不影响推理吧，因为最后会加载pretrained_weights/reference_unet.pth的权重

**Comment by Lizhenghe-Chen** [comment]
https://github.com/antgroup/echomimic_v2/issues/85#issuecomment-2883180890
