### ISSUE TITLE
Some weights of the model checkpoint were not used when initializing UNet2DConditionModel:

### ISSUE THREAD

**Issue by Kimthanh27** [antgroup/echomimic_v2#49]
Some weights of the model checkpoint were not used when initializing UNet2DConditionModel:
 ['down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_q.weight, down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_k.weight, down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_v.weight, down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_out.0.weight, down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_out.0.bias, down_blocks.0.attentions.0.transformer_blocks.0.norm2.weight, down_blocks.0.attentions.0.transformer_blocks.0.norm2.bias, down_blocks.0.attentions.1.transformer_blocks.0.attn2.to_q.weight, down_blocks.0.attentions.1.transformer_blocks.0.attn2.to_k.weight, down_blocks.0.attentions.1.transformer_blocks.0.attn2.to_v.weight, down_blocks.0.attentions.1.transformer_blocks.0.attn2.to_out.0.weight, down_blocks.0.attentions.1.transformer_blocks.0.attn2.to_out.0.bias, down_blocks.0.attentions.1.transformer_blocks.0.norm2.weight, down_blocks.0.attentions.1.transformer_blocks.0.norm2.bias, down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_q.weight, down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_k.weight, down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_v.weight, down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_out.0.weight, down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_out.0.bias, down_blocks.1.attentions.0.transformer_bl
 
 i tried to download the exact models. what caused the issues. my gpu is  12vram

**Comment by mengrang** [comment]
it's ok

**Comment by Kimthanh27** [comment]
but it didn't run. it said "errors" then stopped

**Comment by mengrang** [comment]
we update the automatic installation script for Linux, you can try it.

**Comment by zhaoyangsoft** [comment]
@mengrang 哈喽 孟让， 我在windows 上实验， 貌似也报了这个错误， 空闲了帮着看下？

![Image](https://github.com/user-attachments/assets/a2baa17c-5928-468c-9c7f-e4aa8ddabb50)
