### ISSUE TITLE
Is generating just a talking head like in EchoMimic v1 not supported in v2?

### ISSUE THREAD

**Issue by xD0135** [antgroup/echomimic_v2#50]
I tried to generate a talking head from v1 by using its sample assets in v2 and the result is unexpected as you can see in the attached video. Is this not compatible with the work from https://github.com/antgroup/echomimic? If not, is v1 still being actively maintained? Thanks.

https://github.com/user-attachments/assets/e5597f53-c022-40a0-becf-4b0c7148d2ce

**Comment by mengrang** [comment]
pls double check https://github.com/antgroup/echomimic_v2/discussions/40

**Comment by mengrang** [comment]
pls check https://github.com/antgroup/echomimic_v2/discussions/53
