### ISSUE TITLE
生成的视频的胳膊处很奇怪，这是什么原因导致的，有优化空间吗？

### ISSUE THREAD

**Issue by lilivsea** [antgroup/echomimic_v2#52]
用了一张真人的图像生成视频，一条胳膊正常，一条胳膊一会粗一会细，短袖一会长一会短，有什么改进方法吗？

**Comment by lymhust** [comment]
原图和生成的视频方便发一下吗？

**Comment by lilivsea** [comment]
https://github.com/user-attachments/assets/2fad677d-34ee-4d68-8638-8f40d02922b1

![IMG_export_20241127_112808050](https://github.com/user-attachments/assets/b3e361d1-6fc5-4823-b325-459b2d266ef7)

**Comment by lymhust** [comment]
这个应该还是泛化性问题，后续需要更多的数据再优化一下。
