### ISSUE TITLE
Via Pinokio it just says Error when you generate

### ISSUE THREAD

**Issue by DataJuggler** [antgroup/echomimic_v2#56]
Can you have it list the error so it might be solvable and not just say 'Error'.

**Comment by mengrang** [comment]
Can you show your error?

**Comment by DataJuggler** [comment]
All it says is Error

![image](https://github.com/user-attachments/assets/e7540416-b033-4e6a-b1f4-7d309a7aedfb)

**Comment by nitinmukesh** [comment]
@DataJuggler 

You need to copy the log from command prompt and paste here

**Comment by DataJuggler** [comment]
I am using Pinokio, there is no command prompt.
