### ISSUE TITLE
不是说能生成50秒视频吗，为什么我用45秒的音频驱动，参数length也设置为2000了，只能生成13秒的视频

### ISSUE THREAD

**Issue by helloworlda756** [antgroup/echomimic_v2#58]
不是说能生成50秒视频吗，为什么我用45秒的音频驱动，参数length也设置为2000了，只能生成13秒的视频
能不能生成50秒的视频，还是说我哪里设置错了

**Comment by AIFSH** [comment]
因为目前官方的代码和手势帧数绑定的，你可以 b 站搜索看看有没有第三方解决方案

**Comment by mengrang** [comment]
最近会更新demo，包含pose自定义内容

**Comment by atlasroben** [comment]
最直接的方式,循环使用自带的13秒pose文件以适配长视频:修改app.py以下两处代码:
  1.
    将length = min(length, int(audio_clip.duration * fps), len(os.listdir(inputs_dict['pose'])))修改为
    length = min(length, int(audio_clip.duration * fps))
    available_pose_frames = len(os.listdir(inputs_dict['pose']))
    
2. for index in range(start_idx, start_idx + length):
        pose_idx = index % available_pose_frames  # 当超出范围时，取模以实现循环
        tgt_musk = np.zeros((width, height, 3)).astype('uint8')
        tgt_musk_path = os.path.join(inputs_dict['pose'], "{}.npy".format(pose_idx))#替换原有index
