### ISSUE TITLE
Any way to reduce memory

### ISSUE THREAD

**Issue by nitinmukesh** [antgroup/echomimic_v2#6]
EchoMimic v1 work fine, I use it all the time.

Inference start but did not move forward, waited for long time. It's on 8 GB VRAM.

Anyway to use cpu offload or any other trick like reducing batch size..etc

```
latents shape:torch.Size([1, 4, 149, 96, 96]), video_length:149
  0%|                                                                      | 0/30 [43:23<?, ?it/s]
```

**Comment by mengrang** [comment]
accelerated version will be released asap

**Comment by nitinmukesh** [comment]
Thank you @mengrang.

Can't wait to try accelerated version.

Thank you for releasing EchoMimic. It produces very very good output.
Pass on my thanks to your team.

**Comment by oisilener1982** [comment]
i hope you make a tutorial about how to install v2

**Comment by nitinmukesh** [comment]
> i hope you make a tutorial about how to install v2

I was planning but it didn't worked. Now waiting for accelerated version.

**Comment by mengrang** [comment]
Installation tutorial is updated in readme

**Comment by mengrang** [comment]
About 13G memory is needed

**Comment by oisilener1982** [comment]
> > i hope you make a tutorial about how to install v2
> 
> I was planning but it didn't worked. Now waiting for accelerated version. Good news is mengrang added "doing" label, so it's in progress.

I managed to make it work but my PC cant handle echomimic v2. 
10GB is not enough and it used the Shared GPU memory that take forever to generate
