### ISSUE TITLE
I used a 50 second audio driver and set the length to 2000, why can only generate a 13 second video

### ISSUE THREAD

**Issue by helloworlda756** [antgroup/echomimic_v2#60]
I used a 50 second audio driver and set the length to 2000, why can only generate a 13 second video

**Comment by mengrang** [comment]
u only use the 13s' pose files. pls double check [https://github.com/antgroup/echomimic_v2/discussions/53](https://github.com/antgroup/echomimic_v2/discussions/53)

**Comment by mengrang** [comment]
we will update demo involves pose extracting, or u could extract long pose sequence by yourself
