### ISSUE TITLE
preprocess自定义数据处理 ，缺少依赖

### ISSUE THREAD

**Issue by SevenMpp** [antgroup/echomimic_v2#63]
preprocess.py 文件中引用from src.models.dwpose.dwpose_detector import dwpose_detector as dwprocessor，但是models下面没有相关依赖

**Comment by AIFSH** [comment]
#64

**Comment by mengrang** [comment]
感谢关注我们的工作。目前关于pose的反响很大，所以我们准备将把这一部分（pose提取）集成到jupyter notebook中，这一demo在开发中，近期会更新，详情请看[#40 ](https://github.com/antgroup/echomimic_v2/discussions/40)问题5.

**Comment by mengrang** [comment]
https://github.com/antgroup/echomimic_v2/blob/main/demo.ipynb
