### ISSUE TITLE
Failed to customize the width/height when using app.py

### ISSUE THREAD

**Issue by XieJJ99** [antgroup/echomimic_v2#66]
When using app.py and then set the video width/height other than 768, the runtime throws an exception, complains ValueError like :
ValueError: could not broadcast input array from shape (768,768,3) into shape (386,386,3)
At first, the resolution defined in the .pny file contains the following definition:
```JSON
 "draw_pose_params": [768, 768, 0, 768, 0, 768]
```
The error probably relate to the following :
```Python
        detected_pose = np.load(tgt_musk_path, allow_pickle=True).tolist()        
        imh_new, imw_new, rb, re, cb, ce = detected_pose['draw_pose_params']
        im = draw_pose_select_v2(detected_pose, imh_new, imw_new, ref_w=800)
```
Please note imh_new, imw_new, rb, re, cb, ce  are fixed values read from the .pny file.

Since the musk image shape is defined as the specified:
```Python
        tgt_musk = np.zeros((width, height, 3)).astype('uint8')
```

So the following code always throws an error since the shapes of tgt_musk/im are not match.
```Python
tgt_musk[rb:re,cb:ce,:] = im
```
So probaly we need to downscale the pose at first?

**Comment by mengrang** [comment]
We recommend to set the size of RefImage as 768.

**Comment by XieJJ99** [comment]
@mengrang  Thanks for the quick response, but the issue should remain open.
A few things needed to be clarified:
1. At first, the w=800 setting is in the latest code, I didn't change any code
2. Even if we set w=768, it still says "ValueError: could not broadcast input array from shape (768,768,3) into shape (192,192,3)".
Here's the screen shoot:
![图片](https://github.com/user-attachments/assets/991234f0-c264-4028-944c-4461c09abe6e)
The app.py console:
![图片](https://github.com/user-attachments/assets/104277e3-201a-4273-9579-b43ff9a35eff)

**Comment by XieJJ99** [comment]
Thanks for the update.
The UI only says "Multiples of 16, recommended 768", it doesn't say "must set to 768", and 192=16*12, so the parameters are fine?
Also, I adusted the parameters from 768 to 192 is caused by the performance.
It's take me more than one hour to generate a video in 17 seconds even with a 32GB A100(The resolution of the input image is 1024x1024, and the steps is set to 30 according to the recommendations).
> <img alt="截屏2024-12-02 09 56 59" width="824" src="https://private-user-images.githubusercontent.com/32544247/391386211-c12d149e-a3d8-42c9-9f70-51734e918089.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMDU1MzIsIm5iZiI6MTczMzEwNTIzMiwicGF0aCI6Ii8zMjU0NDI0Ny8zOTEzODYyMTEtYzEyZDE0OWUtYTNkOC00MmM5LTlmNzAtNTE3MzRlOTE4MDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDAyMDcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0ZmM3ODgzMDhiYTYwYWNjYjIxMDNjZmVmNGM2OTVlZGM0ZmUyYzg3ZDJkYjBkMTc3ZWU3NjM0ZjM5NjU0YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yBfonTf711CIyI983bjjKCKr6h9Djnu9pas6EP35maU"> Pls double check your settings

**Comment by XieJJ99** [comment]
@mengrang  Any update on this?
