### ISSUE TITLE
/pretrained_weights/sd-vae-ft-mse is not the path to a directory

### ISSUE THREAD

**Issue by jiten634** [antgroup/echomimic_v2#68]
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like ./pretrained_weights/sd-vae-ft-mse is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.

**Comment by mengrang** [comment]
We recommend to use [linux_setup.sh](https://github.com/antgroup/echomimic_v2/blob/main/linux_setup.sh) to install the project.

**Comment by mHamzaIqbal1998** [comment]
Facing same issue I'm setting up on windows machine. I did follow all steps mention in Readme.

> We recommend to use [linux_setup.sh](https://github.com/antgroup/echomimic_v2/blob/main/linux_setup.sh) to install the project.

**Comment by jiten634** [comment]
> Facing same issue I'm setting up on windows machine. I did follow all steps mention in Readme.
> 
> > We recommend to use [linux_setup.sh](https://github.com/antgroup/echomimic_v2/blob/main/linux_setup.sh) to install the project.

I found the solution, you have to do little struggle. download **pinokio** and then from there you have to install echomimic_v2. then once installed, you can either use it from **pinokio** but it uses the ram everytime, no matter you are using it or not. 
So i copied the **pretrained_weights** from the pinokio installed files.
