### ISSUE TITLE
下载weights失败

### ISSUE THREAD

**Issue by RAYaaaaaaaaaaaaa** [antgroup/echomimic_v2#71]
连不连vpn  在下载weights都显示git lfs install
[git clone https://huggingface.co/BadToBest/EchoMimicV2 pretrained_weights](fatal: unable to access 'https://huggingface.co/BadToBest/EchoMimicV2/': Failed to connect to huggingface.co port 443 after 21061 ms: Couldn't connect to server)是怎么回事啊
<img width="876" alt="企业微信截图_20241202111836" src="https://github.com/user-attachments/assets/f6fad706-a8e3-44f7-bd9d-2abb0d45d850">

**Comment by mengrang** [comment]
可以在讨论群里问一问

**Comment by RAYaaaaaaaaaaaaa** [comment]
没有群呀

**Comment by mengrang** [comment]
<img width="901" alt="截屏2024-12-03 11 59 40" src="https://github.com/user-attachments/assets/98652ba9-c51e-4aff-be51-ecce144c81be">

**Comment by RAYaaaaaaaaaaaaa** [comment]
哇哦  谢谢  知道啦(●ˇ∀ˇ●)
