### ISSUE TITLE
请问生成的视频闪烁是什么原因呢

### ISSUE THREAD

**Issue by wangzf18** [antgroup/echomimic_v2#73]
生成的视频感觉一直在闪，请问大佬是什么原因造成的呢

**Comment by mengrang** [comment]
可以把你的参考图和示例发给我们看一下

**Comment by hnsywangxin** [comment]
同样的问题，是那种轻微的闪动

**Comment by mengrang** [comment]
可以把你们的case、参考图发给我们看一下

**Comment by HeathHose** [comment]
@mengrang  示例视频就有闪烁的感觉，盯着背景看，尤为明显

**Comment by slash130** [comment]
是因为生成每一帧图像时无法做到背景完全一致导致的吗？

**Comment by hnsywangxin** [comment]
@slash130 看着是的，可能从vae编码再解码，就会导致背景有些微差异，从而导致这种现象，不知道我理解的对不对

**Comment by slash130** [comment]
@hnsywangxin 如果用绿幕背景的图片，生成视频之后走抠图流程再合成背景应该会好点，就是有点麻烦。

**Comment by hnsywangxin** [comment]
@slash130 嗯，算是一个trick

**Comment by slash130** [comment]
@hnsywangxin 刚试了一下绿幕图片，人也闪烁，这想法不行。

**Comment by hnsywangxin** [comment]
> @hnsywangxin 刚试了一下绿幕图片，人也闪烁，这想法不行。
背景不闪烁了，人体部分闪烁是不是没那么明显了，不仔细看是不是还可以，另外给人体在帧与帧之间做个平滑或者轻微模糊不知道会不会有改善，比如像素值取个平均？

**Comment by lymhust** [comment]
可以参考一下这个文档：https://github.com/antgroup/echomimic_v2/discussions/40  3. 生成视频噪点问题
