### ISSUE TITLE
在官方 dwpose 之前，先看看平替吧

### ISSUE THREAD

**Issue by AIFSH** [antgroup/echomimic_v2#76]
那个支持自定义手势、分片推理的EchoMimicV2节点开源啦，https://github.com/AIFSH/EchoMimicV2-ComfyUI
【AI浮世绘免费课程第2课从源码安装EchoMimicV2节点，真手把手，免费带你在Windows系统安装，支持自定义手势】 https://www.bilibili.com/video/BV1iUz2YPER7

**Comment by wentao-uw** [comment]
[https://github.com/AIFSH/EchoMimicV2-ComfyUI；](https://github.com/AIFSH/EchoMimicV2-ComfyUI%EF%BC%9B) 这个404了

**Comment by AIFSH** [comment]
去掉；

**Comment by mengrang** [comment]
https://github.com/antgroup/echomimic_v2/blob/main/demo.ipynb
