### ISSUE TITLE
gradio应用app.py中，生成视频超时导致输出视频控件video_output不更新，用户看不到输出

### ISSUE THREAD

**Issue by liaoweiguo** [antgroup/echomimic_v2#78]
generate_button.click(
        generate,
        inputs=[image_input, audio_input, pose_input, width, height, length, steps, sample_rate, cfg, fps, context_frames, context_overlap, quantization_input, seed],
        outputs=[video_output, seed_text],
    )

有办法吗

**Comment by Liliu1997** [comment]
same problem
