### ISSUE TITLE
调用API出错：Value error, The 'meta' field must be explicitly provided in the input data and be equal to.......

### ISSUE THREAD

**Issue by Xwdgood** [antgroup/echomimic_v2#80]
Value error, The 'meta' field must be explicitly provided in the input data and be equal to {'_type': 'gradio.FileData'}. [type=value_error, input_value={'path': '/tmp/gradio/f0c...io_20241205_095059.wav'}, input_type=dict]     For further information visit https://errors.pydantic.dev/2.10/v/value_error

**Comment by mengrang** [comment]
您好，请问是什么api，我们没有发布过api
