### ISSUE TITLE
量化对显存和速度都没多大意义

### ISSUE THREAD

**Issue by liaoweiguo** [antgroup/echomimic_v2#81]

**Comment by mengrang** [comment]
请细说

**Comment by nitinmukesh** [comment]
@mengrang 

I guess he meant to say that even after quantization applied there is no significant reduction in required memory and processing time is also slow.

Please have you finalized the dates for release of Accelerated models. I am looking forward to using it on 8 GB VRAM system. I use EchoMimic all the time and it works really well quality wise.
