### ISSUE TITLE
it took 51 hours to make a 26s video, while 20-30 minutes to make a 10s video 

### ISSUE THREAD

**Issue by trustmiao** [antgroup/echomimic_v2#84]
gpu is 3090. while making a 10s video, everything is fine 78.77/it, took 20-30 minutes. but after I copy & paste to loop the poses, and make a 26s video , it becomes 6125s /it, took totally 51 hours to complete. The result looks just same as 10s.

**Comment by i-amgeek** [comment]
@trustmiao was your GPU using full compute during the entire duration of 51 hours?
