### ISSUE TITLE
cannot import name 'quantize_' from 'torchao.quantization'

### ISSUE THREAD

**Issue by Martin202412** [antgroup/echomimic_v2#86]
> python app.py
RuntimeError: Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
cannot import name 'quantize_' from 'torchao.quantization'

**Comment by ch-yan** [comment]
Did you run this on Windows OS? I came across a post mentioning that the Windows version of torchao might be outdated.

**Comment by pengpengzi** [comment]
> Did you run this on Windows OS? I came across a post mentioning that the Windows version of torchao might be outdated.

same  issue

**Comment by mengrang** [comment]
We recommend to use the linux_setup.sh to install this project.
