### ISSUE TITLE
dwpose问题 源码中的SRC文件目录下并没有 dwpose 出现 ModuleNotFoundError: No module named 'src.models.dwpose'

### ISSUE THREAD

**Issue by PiaoGengHan** [antgroup/echomimic_v2#88]
于是我在虚拟环境中pip install dwpose 并将虚拟环境中的dwpose文件复制到src文件下面 出现ModuleNotFoundError: No module named 'src.models.dwpose.dwpose_detector'
这个dwpose模块需要在哪里下载呢

**Comment by mengrang** [comment]
这是pose提取环节所需项。这几天我们发布notebook脚本，应该可以回答你的真正需要。
