### ISSUE TITLE
AttributeError: 'EchoMimicV2Pipeline' object has no attribute 'pose_enocder'

### ISSUE THREAD

**Issue by AIFSH** [antgroup/echomimic_v2#9]
do you checked the infer.py ? so many bugs

**Comment by holasyb** [comment]
pose_enocder_tensor = self.pose_encoder(poses_tensor)

**Comment by gluttony-10** [comment]
> do you checked the infer.py ? so many bugs

I fix some bugs. See the PR.

**Comment by zhuzcuolis** [comment]
[csdn](https://blog.csdn.net/weixin_50735744/article/details/143953230)
The third question in this article raises this issue.
In the class EchoMimicV2Pipeline, when looking for "pose_enocder" to change to "pose_encoder", it might just be a simple typo.

**Comment by zc388** [comment]
i change it to pose_encoder,it' fine

**Comment by mengrang** [comment]
fixed

**Comment by Rahmaaaa983** [comment]
did you find the pose_encoder.pth please ?
