### ISSUE TITLE
Hands at completely wrong position

### ISSUE THREAD

**Issue by csimlinger** [antgroup/echomimic_v2#90]
I am trying to use the tool and made it only work once. This was, when on the input image no hands were visible.
Once I try to recreate the demo images, the hands are completely off.

Please see the input image and a screenshot of the result here:

![input](https://github.com/user-attachments/assets/c91e5805-0e6f-4680-a898-cf4b67a20e29)

![image](https://github.com/user-attachments/assets/838b75a2-3f5a-42e8-a20d-3d00c1bd6882)

Any idea how to overcome that issue?

Thanks!

**Comment by mengrang** [comment]
The reference image aligned demo will be released, in which hands will be aligned to right position. Please stay tuned.

**Comment by mengrang** [comment]
https://github.com/antgroup/echomimic_v2/blob/main/demo.ipynb

**Comment by csimlinger** [comment]
Thanks, mengrang. To be honest I don't know/understand what to do with the link you provided. Could you please give me brief instructions? Thanks a lot!

**Comment by csimlinger** [comment]
Thanks, mengrang.

I am not sure how to deal with that file.
Can I use the reference image alignment on the GUI which runs on my machine? 

Thanks again!

**Comment by lymhust** [comment]
please refer to this Q&A: https://github.com/antgroup/echomimic_v2/discussions/53
