### ISSUE TITLE
NO Config.json

### ISSUE THREAD

**Issue by xyf12123** [antgroup/echomimic_v2#91]
![1734347412725](https://github.com/user-attachments/assets/22452bc3-91cc-4284-9c4f-f259e97671fa)
sd-image-variations-diffusers中没有config.json文件
查看hf仓库，确实也缺少config.json
![1734347484170](https://github.com/user-attachments/assets/15dca032-2be0-4d4a-9d5f-afffd207341f)

**Comment by xyf12123** [comment]
已经是最新版echomimic_v2版本代码。

**Comment by 13576245149** [comment]
请问这个是怎么解决的, 我也遇到了这个问题

**Comment by krmao** [comment]
解决了吗，我也遇到了
