### ISSUE TITLE
How to use it with non square resolutions?

### ISSUE THREAD

**Issue by KaiwalPanchal** [antgroup/echomimic_v2#95]
i wanted to try to run the model with non-square resolution but it always ends up throwing certain tensor error "The size of tensor a (240) must match the size of tensor b (134) at non-singleton dimension 4".

I was trying to run it for 1980*1080 image, I tried adjust resolution to make it 1980*1072 to make it divisible by 16 but it still didn't work.

how can I resolve it???

**Comment by mengrang** [comment]
You could try to use the latest released demo.ipynb to adapt the size of reference image
